// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { AuthProvider } from "@/app/context/AuthContext"; // Adjust the path as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <nav>
            <Nav />
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
